chore: add mock task for tests
smartvokat/sagax pull request #3
Opened 2021-01-29 11:16 UTC by gaynetdinov

With introduction of `transaction/2` it became harder to test sagas
wrapped into a database transaction. The issue is that once you have
a test which spawns a new process which needs to talk to a database
within a transaction, this process cannot obtain a database connection.

```
ExUnit process -> ExUnit transaction -> Sagax transaction -> Task.async -> SQL query from Sagax stage -> error!
```

This somewhat hacky way of mocking Task module should fix the issue.

2021-01-29 14:41 UTC, gaynetdinov commented on lib/sagax.ex
> +        {:error, reason, %{saga | executed?: true, state: :error, last_result: reason, queue: []}}
I noticed that in case of failure `execute/3` returns `{:error, reason, saga}`. Here, with `transaction/2` I broke the interface.
@madebyherzblut can you please help me understand the details here? 
- should we put `reason` as `last_result` here even though we return `reason` as a dedicated element in the tuple? 
- should saga be marked as `executed?: true`? I've seen that sometimes failed sagas are not marked as `executed?: true`

2021-02-01 08:40 UTC, madebyherzblut requested changes

2021-02-01 08:40 UTC, madebyherzblut commented on lib/sagax/executer.ex
> +  @task Application.get_env(:sagax, :task_module, Task)
I think this should be moved to the function, since module attributes are resolved during compilation and this might suprise the consumer of the library (even though it is not a problem in this case). What do you think?

2021-02-01 08:40 UTC, madebyherzblut commented on lib/sagax.ex
> +        {:error, reason, %{saga | executed?: true, state: :error, last_result: reason, queue: []}}
Ah, yeah, it is confusing. I don't have a strong opinion of whether we should go with a 2 or 3 elements tuple for the error response. From a consumer perspective, the 3 elements tuple might be a bit easier (or more convenient) to pattern match.

A saga should always be marked as `executed` regardless of success or failure. If that is not the case, we should fix that.

2021-02-01 09:07 UTC, gaynetdinov commented on lib/sagax/executer.ex
> +  @task Application.get_env(:sagax, :task_module, Task)
Yeah, I was thinking about that and thought that compile-time would work here, but I can move it to a function for sure.

2021-02-01 09:08 UTC, gaynetdinov commented on lib/sagax.ex
> +        {:error, reason, %{saga | executed?: true, state: :error, last_result: reason, queue: []}}
Ok thanks, I'll try to reproduce a case when I've seen failed saga with `executed?` being false.

2021-02-01 09:30 UTC, madebyherzblut approved these changes

2021-02-01 10:00 UTC, merged