Add `Builder` for `Sagax.Next`
smartvokat/sagax pull request #9
Opened 2021-10-27 09:53 UTC by gaynetdinov

Add a `Builder` module that should make it easier to execute sagas.

2021-11-02 08:56 UTC, madebyherzblut commented on lib/next.ex
> +  @spec execute(Sagax.t()) :: Sagax.t()
The ideal solution for me would be that each error contains the path. Lets imagine the following example:

- `saga CreateAndSubscribeUser`
	- `put :user CreateUser`
	  - `run AssignTenant`
	- `put :plan CreatePlan`
	- `run ChargeUser`

When the error happend in `AssignTenant` the saga result would be `[%Sagax.Error{path: [:user], error: error_value_returned_by_saga]}`. Is something like this possible?

2021-11-02 14:21 UTC, gaynetdinov commented on lib/next/executer.ex
> +    do_compensate(state)
I cannot think of any other case when we might have multiple errors return except the case when an error occurred, then we started iterating over compensations and one of the iterations failed too. Then I'd expect we should return multiple errors (the original one plus compensation). For that, I had to change this `do_compensate` function and call `State.apply` from it in order to store any potential result of the `comp` function.

2021-11-02 14:24 UTC, gaynetdinov commented on lib/next/state.ex
> +  def apply(%State{values: values, errors: errors} = state, operation, {:error, result})
Right now, this function is going to be used both by erroneous saga steps and compensations.
Here, we store the `result` (which can be both a result of the erroneous saga step or a result of comp function executed) into `values` and `errors`. What if we generally stop storing erroneous results into `values` and store them only in `errors`? Since we're going to return `{:error, errors}` in case of an error, it does not make sense to store a `result` here both in `values` and `errors` if you ask me.

2021-11-03 10:12 UTC, madebyherzblut commented on lib/next/executer.ex
> +    do_compensate(state)
As soon as we add async effects again we may also have multiple errors, so I think using a list is the right way to go.

2021-11-03 10:13 UTC, madebyherzblut commented on lib/next/state.ex
> +  def apply(%State{values: values, errors: errors} = state, operation, {:error, result})
Yes, appending errors only to `errors` and leave the `values` untouched makes the most sense to me as well 👍

2021-11-03 10:20 UTC, madebyherzblut requested changes
Only one question from my side about the return values. Otherwise we are good to go 👍

2021-11-03 10:20 UTC, madebyherzblut commented on lib/next/executer.ex
> +    end
What do you think of keeping the spec`Executer.execute(Sagax.t()) :: Sagax.t()` and do the split into `{:ok, value} | {:error, errors}` inside `Sagax.execute`. Since the `Executer` is internal it makes sense to me to return the whole saga again, because there may be meta information etc. in there.

2021-11-03 10:20 UTC, madebyherzblut commented on lib/next/builder.ex
> +      @spec execute(any, any, []) :: Sagax.Next.t()
```suggestion
      @spec execute(map(), map(), Keyword.t()) :: {:ok, any()} | {:error, [Sagax.Next.Error.t()]
```

2021-11-03 10:20 UTC, madebyherzblut commented on lib/next.ex
> +  @spec execute(Sagax.t()) :: Sagax.t()
```suggestion
  @spec execute(map(), map(), Keyword.t()) :: {:ok, any()} | {:error, [Sagax.Next.Error.t()]
```

2021-11-03 12:41 UTC, madebyherzblut approved these changes

2021-11-03 12:44 UTC, merged

2021-11-03 12:45 UTC, gaynetdinov commented
🎉